version: '2'

services:
  app:
    mem_limit: 500M
    build:
      context: ./
      dockerfile: Dockerfile
    command: python server.py
    volumes:
      - ./test_photos:/app/photos
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    environment:
      PORT: 8080
      PHOTOS_DIR: /app/photos
